// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCw-CMDHcWLvlNabMnN0DaIrD0h_Arb5fI',
    appId: '1:297588094368:web:70269a3e6bc0c124f3a0c5',
    messagingSenderId: '297588094368',
    projectId: 'sw-aid-for-med-emergencies',
    authDomain: 'sw-aid-for-med-emergencies.firebaseapp.com',
    storageBucket: 'sw-aid-for-med-emergencies.appspot.com',
    measurementId: 'G-K4P25M970R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEYuIgosmEdPCb2j2ovNuuOiF_FjNSqlU',
    appId: '1:297588094368:android:dde785c44ab371def3a0c5',
    messagingSenderId: '297588094368',
    projectId: 'sw-aid-for-med-emergencies',
    storageBucket: 'sw-aid-for-med-emergencies.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtugRHwjVPTVb0QdObYGO-CrUtun_Qak4',
    appId: '1:297588094368:ios:ba0296d9543ca43bf3a0c5',
    messagingSenderId: '297588094368',
    projectId: 'sw-aid-for-med-emergencies',
    storageBucket: 'sw-aid-for-med-emergencies.appspot.com',
    iosBundleId: 'com.example.sAMe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtugRHwjVPTVb0QdObYGO-CrUtun_Qak4',
    appId: '1:297588094368:ios:2fd9a8bb37f56649f3a0c5',
    messagingSenderId: '297588094368',
    projectId: 'sw-aid-for-med-emergencies',
    storageBucket: 'sw-aid-for-med-emergencies.appspot.com',
    iosBundleId: 'com.example.sAMe.RunnerTests',
  );
}
